version: '3.3'
services:

  NetworkMapAndNotary:
    networks:
      - corda
    build:
      context: ./nodes/NetworkMapAndNotary
      args:
        BUILDTIME_CORDA_VERSION: corda-3.0
    env_file:
      - ./corda_docker.env
    ports:
      - "10002:10002"
    image: corda/networkmapandnotary:3.0
    container_name: NetworkMapAndNotary 
    volumes:
      - ./nodes/NetworkMapAndNotary/node.conf:/opt/corda/node.conf
      - ./nodes/NetworkMapAndNotary/network-parameters:/opt/corda/network-parameters
      - ./nodes/NetworkMapAndNotary/certificates/:/opt/corda/certificates/

  PartyA:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: corda-3.0
    env_file:
      - ./corda_docker.env
    ports:
      - "10005:10005"
      - "10006:10006"
      - "10046:10046"
      - "10007:10007"
    image: corda/node:3.0
    container_name: PartyA
    volumes:
      - ./nodes/PartyA/node.conf:/opt/corda/node.conf
      - ./cordapps/:/opt/corda/cordapps/
      - ./nodes/PartyA/network-parameters:/opt/corda/network-parameters
      - ./nodes/PartyA/certificates/:/opt/corda/certificates/
    depends_on:
      - NetworkMapAndNotary

  PartyB:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: corda-3.0
    env_file:
      - ./corda_docker.env
    ports:
      - "10008:10008"
      - "10009:10009"
      - "10049:10049"
      - "10010:10010"
    image: corda/node:3.0
    container_name: PartyB
    volumes:
      - ./nodes/PartyB/node.conf:/opt/corda/node.conf
      - ./nodes/PartyB/network-parameters:/opt/corda/network-parameters
      - ./cordapps/:/opt/corda/cordapps/
      - ./nodes/PartyB/certificates/:/opt/corda/certificates/
    depends_on:
      - NetworkMapAndNotary

networks:
  corda:
