version: '3.3'
services:
  Notary:
    networks:
      corda:
        ipv4_address: 10.5.0.5
    build:
      context: ./nodes/Notary
      args:
        BUILDTIME_CORDA_VERSION: corda-3.0
    env_file:
      - ./corda_docker.env
    ports:
      - "10002:10002"
    image: corda/notary:3.0
    container_name: Notary 
    volumes:
      - ./nodes/Notary/node.conf:/opt/corda/node.conf
      - ./nodes/Notary/network-parameters:/opt/corda/network-parameters
      - ./nodes/Notary/additional-node-infos:/opt/corda/additional-node-infos
      - ./nodes/Notary/certificates/:/opt/corda/certificates/

  BMBS:
    networks:
      corda:
        ipv4_address: 10.5.0.6
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: corda-3.0
    env_file:
      - ./corda_docker.env
    ports:
      - "10005:10005"
      - "10006:10006"
      - "10046:10046"
      - "10007:10007"
    image: corda/node:3.0
    container_name: BMBS
    volumes:
      - ./nodes/BMBS/node.conf:/opt/corda/node.conf
      - ./cordapps/:/opt/corda/cordapps/
      - ./nodes/BMBS/network-parameters:/opt/corda/network-parameters
      - ./nodes/BMBS/additional-node-infos:/opt/corda/additional-node-infos
      - ./nodes/BMBS/certificates/:/opt/corda/certificates/
    depends_on:
      - Notary

networks:
  corda:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 10.5.0.0/24
